<p>
    A változók segítségével személyre szabható a sablon.
</p>

<table>
    <thead>
        <tr>
            <th>Vátozó</th>
            <th>Leírás</th>
        </tr>
    </thead>
    <tbody>
    <tr>
        <td><code>%SUBJECT%</code></td>
        <td>Tárgy</td>
    </tr>
    <tr>
        <td><code>%NAME%</code></td>
        <td>Név</td>
    </tr>
    <tr>
        <td><code>%EMAIL%</code></td>
        <td>Email</td>
    </tr>
    <tr>
        <td><code>%MESSAGE%</code></td>
        <td>Üzenet</td>
    </tr>
    </tbody>
</table>
